version: '3.8'  # Version of Docker Compose
services:
  postgres:
    image: postgres:latest
    container_name: newsletter
    ports:
      - "5434:5432"   # Host Port:Container Port
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9090"
