version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: newsletter2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: newsletterdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  backend:
    build:
      context: ./backend
    image: newsletter_backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@postgres:5432/newsletterdb
    depends_on:
      postgres:
        condition: service_healthy
    command: ["sh", "-c", "diesel migration run && /app/newsletter"]

  frontend:
    build:
      context: ./frontend
    image: newsletter_frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  # Uncomment this if you need MinIO
  # minio:
  #   image: minio/minio
  #   container_name: minio
  #   ports:
  #     - "9000:9000"
  #     - "9090:9090"
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #   volumes:
  #     - ~/minio/data:/data
  #   command: server /data --console-address ":9090"
