version: '3.8' 
services:
  postgres:
    image: postgres:latest
    container_name: newsletter2
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  backend:
    build:
      context: ./backend 
    image: newsletter_backend
    container_name: backend
    ports:
      - "8000:8000"  
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@localhost:5432/newsletter
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend # Path to the frontend Dockerfile
    image: newsletter_frontend
    container_name: frontend
    ports:
      - "5173:5173"  # Adjust if your frontend uses a different port
    depends_on:
      - backend


  # minio:
  #   image: minio/minio
  #   container_name: minio
  #   ports:
  #     - "9000:9000"
  #     - "9090:9090"
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #   volumes:
  #     - ~/minio/data:/data
  #   command: server /data --console-address ":9090"
