replicaCount: 1

postgresql:
  databaseName: postgresql

backend:
  image:
    repository: newsletter-k8s_backend
    pullPolicy: IfNotPresent
    tag: latest

frontend:
  image:
    repository: newsletter-k8s_frontend
    pullPolicy: IfNotPresent
    tag: latest

postgresqlVolume:
  persistentVolumeClaim:
    storageSize: 1Gi  

  persistentVolume:
    storageSize: 1Gi  
    pathOnHost: /var/lib/postgresql 


  mountPath: /var/lib/postgresql 