apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgresql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgresql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgresql
    spec:
      containers: # Fixed indentation and structure
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env: # Moved env inside the container spec
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
          volumeMounts: # Corrected indentation
            - name: {{ .Release.Name }}-postgresql-persistent-storage
              mountPath: {{ .Values.postgresqlVolume.mountPath }}
      restartPolicy: Always # `restartPolicy` is defined for the Pod spec
      volumes:
        - name: {{ .Release.Name }}-postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgresql-pvc
