apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-username
type: Opaque
stringData:
  username: root

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-password
type: Opaque
stringData:
  password: root